services:
  network-deploy-service:
    networks:
      - home-work2

  microservice-base-service:
    extends:
      service: network-deploy-service
    environment:
      #      SPRING_RABBITMQ_HOST: "rabbit"
      JAVA_TOOL_OPTIONS: "-javaagent:/app/libs/opentelemetry-javaagent-1.27.0.jar"
      OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo:4317
      OTEL_METRICS_EXPORTER: none
    deploy:
      resources:
        limits:
          memory: 700m

  microservice-config-service:
    extends:
      service: microservice-base-service
    environment:
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      SPRING_PROFILES_ACTIVE: qa
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
#      EUREKA_INSTANCE_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/


