server:
  port: 8071

spring:
  application:
    name: "configserver"
  profiles:
#    active: native
    active: git
  cloud:
    config:
      server:
#        native:
#          search-locations: "classpath:/config"
#          search-locations: "file:///c://Users//einst//workspace//config//"
        git:
          uri: "https://github.com/EinsteinOlivoGit/hw2_config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
    stream:
      kafka:
        binder:
          brokers:
            - kafka:9092

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
    shutdown:
      enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

endpoints:
  shutdown:
    enabled: true

#eureka:
#  instance:
#    preferIpAddress: true
#  client:
#    fetchRegistry: true
#    registerWithEureka: true
#    serviceUrl:
#      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "configserver"
    description: "Example bank application"
    version: "1.0.0"

encrypt:
  key: "Y1Kus5843JFx6eZ5RqDL0PUIGjMOJ8"

logging:
  pattern:
    level: "%5p <${spring.application.name}><%X{trace_id}><%X{span_id}>"